name: "ROI · Registro de Caso"
description: "Registre os números do seu caso real (use os dados da planilha)."
title: "ROI: <Nome do Agente> — <Equipe/Área>"
labels: ["roi", "capsula-6"]
body:
  - type: markdown
    attributes:
      value: |
        **Passo a passo**
        1) Baixe e preencha a planilha de ROI da Cápsula 6  
        2) Anote os resultados (Benefício, Custo, ROI, Payback)  
        3) Preencha os campos abaixo e envie  
        4) (Opcional) Arraste um print da planilha para anexar na issue

  - type: input
    id: agente
    attributes:
      label: Nome do agente
      placeholder: ex.: Assistente de Propostas (SalesOps)
    validations:
      required: true

  - type: input
    id: owner
    attributes:
      label: Responsável (owner)
      placeholder: ex.: Maria Silva (SalesOps)
    validations:
      required: true

  - type: input
    id: valor_hora
    attributes:
      label: Valor/hora (R$)
      placeholder: ex.: 70
    validations:
      required: true

  - type: input
    id: tempo_baseline
    attributes:
      label: Tempo médio por tarefa — baseline (min)
      placeholder: ex.: 45
    validations:
      required: true

  - type: input
    id: tempo_pos
    attributes:
      label: Tempo médio por tarefa — pós-agente (min)
      placeholder: ex.: 20
    validations:
      required: true

  - type: input
    id: tarefas_mes
    attributes:
      label: Tarefas por mês
      placeholder: ex.: 60
    validations:
      required: true

  - type: input
    id: custo_licenca
    attributes:
      label: Custo mensal (licenças) — R$
      placeholder: ex.: 200
    validations:
      required: true

  - type: input
    id: custo_manutencao
    attributes:
      label: Custo mensal (manutenção) — R$
      placeholder: ex.: 100
    validations:
      required: true

  - type: input
    id: custo_setup
    attributes:
      label: Custo de setup (R$) — amortizado em 12 meses
      placeholder: ex.: 1500
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **(Opcional) Qualidade**
        Se você mediu melhora de qualidade, preencha os campos abaixo e informe também o custo médio por erro.

  - type: input
    id: taxa_erro_base
    attributes:
      label: Taxa de erro baseline (%)
      placeholder: ex.: 6
    validations:
      required: false

  - type: input
    id: taxa_erro_pos
    attributes:
      label: Taxa de erro pós-agente (%)
      placeholder: ex.: 3
    validations:
      required: false

  - type: input
    id: custo_erro
    attributes:
      label: Custo médio por erro (R$)
      placeholder: ex.: 50
    validations:
      required: false

  - type: textarea
    id: resultados_planilha
    attributes:
      label: Resultados da planilha (copie e cole)
      description: "Cole aqui os números que a planilha calculou: Benefício (tempo), Benefício (qualidade), Benefício total, Custo mensal, ROI, Payback."
      placeholder: |
        Benefício (tempo): R$ ...
        Benefício (qualidade): R$ ...
        Benefício total: R$ ...
        Custo mensal: R$ ...
        ROI: ... %
        Payback: ... meses
    validations:
      required: true

  - type: textarea
    id: observacoes
    attributes:
      label: Observações (links, anexos, riscos)
      placeholder: Ex.: link para a planilha, print em anexo, riscos e supostos, etc.
    validations:
      required: false

  - type: checkboxes
    id: consent
    attributes:
      label: Publicação dos números no repositório
      options:
        - label: Concordo em publicar estes dados (internos ao curso) no repositório do projeto.
          required: true

  - type: markdown
    attributes:
      value: |
        **Fórmulas (resumo)**
        - Benefício (tempo) = (Tempo_baseline − Tempo_pós) × Tarefas/mês × Valor/hora ÷ 60
        - Benefício (qualidade) = (Taxa_erro_base − Taxa_erro_pós) × Tarefas/mês × Custo_por_erro
        - Benefício total = tempo + qualidade
        - Custo mensal = licenças + manutenção + amortização(setup, 12 meses)
        - ROI = (Benefício − Custo) ÷ Custo
